resolver: lts-13.6
packages:
- .

extra-deps:
  - datetime-sb-0.2.4@sha256:dcd9550de06b1c9646be57993848990bf0f0874c2bdac8357bf65d0e69006322
  - rss-conduit-0.4.3.1@sha256:573866daa73fc1c4f6fd506fc530a887f5251c63dc3f08b9bd98d1c8b706005a
  - atom-conduit-0.5.0.3@sha256:6490c4568dee593a8ef2d377f5393a424ad86ebcf46691ad58e6d1d2f34b9ef8
  - config-value-0.6.3.1@sha256:cc90d51318b3ae633aebe2b099953d75c514a19aeefbf68ceed38d8f983f049a
  - config-schema-0.5.0.1@sha256:7e0fcff8f9174ee34a8281451dab58736a146fe9deeb4e2111492b8542e65580

docker:
  # Set to false to disable using Docker.  In the project configuration,
  # the presence of a `docker:` section implies docker is enabled unless
  # `enable: false` is set.  In user and global configuration, this is not
  # the case.
  enable: true

  # The name of the repository to pull the image from.  See the "repositories"
  # section of this document for more information about available repositories.
  # If this includes a tag (e.g. "my/image:tag"), that tagged image will be
  # used.  Without a tag specified, the LTS version slug is added automatically.
  # Either `repo` or `image` may be specified, but not both.
  repo: "fpco/stack-build"

  # Registry requires login.  A login will be requested before attempting to
  # pull.
  registry-login: false

  # If true, the image will be pulled from the registry automatically, without
  # needing to run `stack docker pull`.  See the "security" section of this
  # document for implications of enabling this.
  auto-pull: false

  # If true, the container will be run "detached" (in the background).  Refer
  # to the Docker users guide for information about how to manage containers.
  # This option would rarely make sense in the configuration file, but can be
  # useful on the command-line.  When true, implies `persist`.
  detach: false

  # If true, the container will not be deleted after it terminates.  Refer to
  # the Docker users guide for information about how to manage containers. This
  # option would rarely make sense in the configuration file, but can be
  # useful on the command-line.  `detach` implies `persist`.
  persist: false

  # What to name the Docker container.  Only useful with `detach` or
  # `persist` true.  (default none)
  container-name: "newsletter"

  # Additional arguments to pass to `docker run`.  (default none)
  run-args: []
  stack-exe: download

  # If true (the default when using the local Docker Engine), run processes
  # in the Docker container as the same UID/GID as the host.  The ensures
  # that files written by the container are owned by you on the host.
  # When the Docker Engine is remote (accessed by tcp), defaults to false.
  set-user: true

  # Require the version of the Docker client to be within the specified
  # Cabal-style version range (e.g., ">= 1.6.0 && < 1.9.0")
  require-docker-version: ">= 1.6.0"
image:

  # You need a `containers` yaml section for `stack image container`.
  # A `container` section that does not contain a list is also valid.
  containers:

    # This example just has one container.
    -
      # You need a base image name. Stack layers exes on top of
      # the base image. Prepare your project image in advance by
      # putting all your runtime dependencies in the image.
      base: "newsletter-base"
      add:
        crontabs: /etc/cron.d
        configs: /etc/newsletter/configs
      executables: [newsletter-exe]
      # Optionally specify a list of executables. Stack will create
      # a tagged image for each in the list. these images will have
      # their respective "ENTRYPOINT" set.